name    'alkivi-zabbix'
version '0.1.1'
source 'https://github.com/alkivi-sas/puppet-zabbix'
author 'alkivi'
license 'LGPLv3'
summary 'Controls Zabbix server,proxy and agent'
description 'Setup Zabbix Server, Proxy or Agent with several custom agent parameters'
project_page 'https://github.com/alkivi-sas/puppet-zabbix'
dependency 'puppetlabs/stdlib', '>=3.0.0'
dependency 'puppetlabs/apt', '>=1.4.2'
dependency 'puppetlabs/mysql', '>=2.0.0'
dependency 'alkivi/alkivi_base', '>=0.1.0'
